### ISSUE TITLE
Some registration numbers not being accepted

### ISSUE THREAD

**Issue by masteradit** [cribbl/miteb-frontend#107]
**Describe the bug**
Some registration numbers not being accepted, for example, 190911112 is not getting accepted while creating an event.

**To Reproduce**
1. Login as a club.
2. Go to Room Booking page.
3. In the registration number field, enter `190911112`.
4. Error `Registration number is not valid` is shown.

**Expected behavior**
It should accept this registration number.

**Screenshots**
![Screenshot from 2020-04-06 14-57-52](https://user-images.githubusercontent.com/39951503/78544133-4d055f00-7817-11ea-9ae4-d55b87ec7e90.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Mozilla Firefox
 - Version 70.0.1

**Additional context**

**Comment by bhawesh96** [comment]
We need to address registration numbers starting from '2' (eg. 200911124).
The current regex doesn't handle this. Let's come up with a generic regex as @rsarky suggested.
@masteradit , can you please take this up?
