### ISSUE TITLE
Allow clubs to cancel bookings.

### ISSUE THREAD

**Issue by rsarky** [cribbl/miteb-frontend#65]
**Is your feature request related to a problem? Please describe.**
Clubs can't cancel booking themselves currently. This feature is required if their event gets cancelled and the rooms need to be freed.

**Comment by Arushi1912** [comment]
1. /events/eventID
2. /users/userID/my_events/eventID
3. /roomsx/date (startDate --> endDate)
4. /to-be-held/date ^^

**Comment by rsarky** [comment]
Ping @nids98 . Update please
